import { googleSheets, spreadsheetId } from "./client";

// Dictionary mapping spreadsheet headers to TypeScript camelCase object keys
const HEADER_TO_KEY_MAP: Record<string, string> = {
  "UUID": "uuid",
  "Student Name": "studentName",
  "Grade": "grade",
  "Board": "board",
  "Parent Name": "parentName",
  "Parent Email": "parentEmail",
  "Parent WhatsApp": "parentWhatsApp",
  "Mentor": "mentor",
  "Academic Coordinator": "academicCoordinator",
  "Enrollment Date": "enrollmentDate",
  "Status": "status",
  "Overall Progress Score": "overallProgressScore",
  "Health Status": "healthStatus",
  "Created At": "createdAt",
  "Updated At": "updatedAt",
  "Subject ID": "subjectId",
  "Subject": "subject",
  "Start Date": "startDate",
  "End Date": "endDate",
  "Class ID": "classId",
  "Student UUID": "studentUuid",
  "Chapter": "chapter",
  "Date": "date",
  "Duration": "duration",
  "Attendance": "attendance",
  "Participation %": "participation",
  "Homework Given": "homeworkGiven",
  "Homework Completed": "homeworkCompleted",
  "Revision Notes Shared": "revisionNotesShared",
  "Remarks": "remarks",
  "Created By": "createdBy",
  "Timestamp": "timestamp",
  "Assignment ID": "assignmentId",
  "Assignment Title": "assignmentTitle",
  "Assigned Date": "assignedDate",
  "Due Date": "dueDate",
  "Submission Status": "submissionStatus",
  "Score": "score",
  "Total Marks": "totalMarks",
  "Percentage": "percentage",
  "Mentor Remarks": "mentorRemarks",
  "Test ID": "testId",
  "Test Name": "testName",
  "Marks Obtained": "marksObtained",
  "Mentor Comment": "mentorComment",
  "Exam ID": "examId",
  "Exam Name": "examName",
  "Marks": "marks",
  "Total": "total",
  "Previous Percentage": "previousPercentage",
  "Improvement %": "improvementPercentage",
  "Plan ID": "planId",
  "Month": "month",
  "Strengths": "strengths",
  "Weak Areas": "weakAreas",
  "Goals": "goals",
  "Mentor Plan": "mentorPlan",
  "Parent Focus": "parentFocus",
  "PTM ID": "ptmId",
  "PTM Date": "ptmDate",
  "Parent Concerns": "parentConcerns",
  "Mentor Recommendations": "mentorRecommendations",
  "Action Items": "actionItems",
  "Next PTM Date": "nextPtmDate",
  "Note ID": "noteId",
  "Notes": "notes",
  "Include In Report": "includeInReport",
  "Report ID": "reportId",
  "Report Type": "reportType",
  "Generated By": "generatedBy",
  "Generated Date": "generatedDate",
  "Drive File ID": "driveFileId",
  "PDF URL": "pdfUrl",
  "Public Token": "publicToken",
  "Public URL": "publicUrl",
  "Mode": "mode",
  "Snapshot Data": "snapshotData",
  "Total Students": "totalStudents",
  "Active Students": "activeStudents",
  "Attendance %": "attendancePercentage",
  "Pending Assignments": "pendingAssignments",
  "Reports Pending": "reportsPending",
  "Average Score": "averageScore",
  "Average Progress": "averageProgress",
  "Students At Risk": "studentsAtRisk",
  "Attendance Weight": "attendanceWeight",
  "Assignment Weight": "assignmentWeight",
  "Participation Weight": "participationWeight",
  "Homework Weight": "homeworkWeight",
  "Chapter Test Weight": "chapterTestWeight",
  "School Exam Weight": "schoolExamWeight",
  "Action": "action",
  "User": "user",
  "Time": "time",
  "Module": "module",
  "Description": "description",
};

// Inverse map for writing records back to Sheet rows
const KEY_TO_HEADER_MAP: Record<string, string> = Object.entries(
  HEADER_TO_KEY_MAP
).reduce((acc, [header, key]) => {
  acc[key] = header;
  return acc;
}, {} as Record<string, string>);

/**
 * Fetch and parse all rows of a worksheet into typed objects.
 */
export async function getRows<T>(sheetName: string): Promise<T[]> {
  try {
    const response = await googleSheets.spreadsheets.values.get({
      spreadsheetId,
      range: `${sheetName}!A1:Z`,
    });

    const rows = response.data.values;
    if (!rows || rows.length === 0) return [];

    const headers = rows[0];
    const dataRows = rows.slice(1);

    return dataRows.map((row) => {
      const obj: Record<string, any> = {};
      headers.forEach((header, index) => {
        const key = HEADER_TO_KEY_MAP[header] || header;
        let value = row[index] !== undefined ? row[index] : "";

        // Parse boolean strings and numbers automatically
        if (value === "TRUE") value = true;
        else if (value === "FALSE") value = false;
        else if (value !== "" && !isNaN(Number(value)) && key !== "parentWhatsApp" && key !== "uuid" && !key.endsWith("Id")) {
          value = Number(value);
        }

        obj[key] = value;
      });
      return obj as T;
    });
  } catch (error: any) {
    console.error(`Error getting rows from sheet ${sheetName}:`, error.message);
    throw error;
  }
}

/**
 * Appends a new row object to the worksheet, matching the columns headers order.
 */
export async function addRow(
  sheetName: string,
  data: Record<string, any>
): Promise<void> {
  try {
    // 1. Fetch headers to match columns precisely
    const headerResponse = await googleSheets.spreadsheets.values.get({
      spreadsheetId,
      range: `${sheetName}!A1:1`,
    });

    const headers = headerResponse.data.values?.[0];
    if (!headers || headers.length === 0) {
      throw new Error(`Sheet ${sheetName} has no headers or does not exist.`);
    }

    // 2. Map data object to row array matching header order
    const newRow = headers.map((header) => {
      const key = HEADER_TO_KEY_MAP[header] || header;
      const val = data[key];
      if (val === true) return "TRUE";
      if (val === false) return "FALSE";
      return val !== undefined ? String(val) : "";
    });

    // 3. Append to Google Sheet
    await googleSheets.spreadsheets.values.append({
      spreadsheetId,
      range: `${sheetName}!A2`,
      valueInputOption: "USER_ENTERED",
      requestBody: {
        values: [newRow],
      },
    });
  } catch (error: any) {
    console.error(`Error adding row to sheet ${sheetName}:`, error.message);
    throw error;
  }
}

/**
 * Updates a row where keyColumn matches keyValue.
 */
export async function updateRow(
  sheetName: string,
  keyColumn: string,
  keyValue: string,
  data: Record<string, any>
): Promise<void> {
  try {
    // 1. Fetch all rows including headers
    const response = await googleSheets.spreadsheets.values.get({
      spreadsheetId,
      range: `${sheetName}!A1:Z`,
    });

    const rows = response.data.values;
    if (!rows || rows.length === 0) {
      throw new Error(`Sheet ${sheetName} is empty.`);
    }

    const headers = rows[0];
    const keyIndex = headers.indexOf(keyColumn);
    if (keyIndex === -1) {
      throw new Error(`Key column ${keyColumn} not found in sheet ${sheetName}.`);
    }

    // 2. Find matching row index (1-indexed + 1 to account for header offset)
    let rowIndex = -1;
    for (let i = 1; i < rows.length; i++) {
      if (rows[i][keyIndex] === keyValue) {
        rowIndex = i + 1; // Row number in spreadsheet (2-indexed base)
        break;
      }
    }

    if (rowIndex === -1) {
      throw new Error(
        `Row with key ${keyColumn} = ${keyValue} not found in sheet ${sheetName}.`
      );
    }

    // 3. Construct updated values matching header order (merge existing row data)
    const existingRow = rows[rowIndex - 1];
    const updatedRow = headers.map((header, index) => {
      const key = HEADER_TO_KEY_MAP[header] || header;
      if (data[key] !== undefined) {
        const val = data[key];
        if (val === true) return "TRUE";
        if (val === false) return "FALSE";
        return String(val);
      }
      return existingRow[index] !== undefined ? String(existingRow[index]) : "";
    });

    // 4. Update the range for the specific row
    const range = `${sheetName}!A${rowIndex}:${String.fromCharCode(
      65 + headers.length - 1
    )}${rowIndex}`;
    await googleSheets.spreadsheets.values.update({
      spreadsheetId,
      range,
      valueInputOption: "USER_ENTERED",
      requestBody: {
        values: [updatedRow],
      },
    });
  } catch (error: any) {
    console.error(`Error updating row in sheet ${sheetName}:`, error.message);
    throw error;
  }
}

/**
 * Deletes a row where keyColumn matches keyValue by deleting its row index.
 */
export async function deleteRow(
  sheetName: string,
  keyColumn: string,
  keyValue: string
): Promise<void> {
  try {
    // 1. Fetch all rows
    const response = await googleSheets.spreadsheets.values.get({
      spreadsheetId,
      range: `${sheetName}!A1:Z`,
    });

    const rows = response.data.values;
    if (!rows || rows.length === 0) return;

    const headers = rows[0];
    const keyIndex = headers.indexOf(keyColumn);
    if (keyIndex === -1) return;

    // 2. Find row index (0-indexed relative to data rows)
    let indexToDelete = -1;
    for (let i = 1; i < rows.length; i++) {
      if (rows[i][keyIndex] === keyValue) {
        indexToDelete = i; // 0-indexed row number in the list
        break;
      }
    }

    if (indexToDelete === -1) return;

    // 3. Resolve the numeric sheetId for the sheet title
    const sheetMeta = await googleSheets.spreadsheets.get({
      spreadsheetId,
    });
    const targetSheet = sheetMeta.data.sheets?.find(
      (s) => s.properties?.title === sheetName
    );
    const sheetId = targetSheet?.properties?.sheetId;

    if (sheetId === undefined) {
      throw new Error(`Could not resolve sheetId for ${sheetName}`);
    }

    // 4. Send request to delete the row dimension
    await googleSheets.spreadsheets.batchUpdate({
      spreadsheetId,
      requestBody: {
        requests: [
          {
            deleteDimension: {
              range: {
                sheetId,
                dimension: "ROWS",
                startIndex: indexToDelete,
                endIndex: indexToDelete + 1,
              },
            },
          },
        ],
      },
    });
  } catch (error: any) {
    console.error(`Error deleting row from sheet ${sheetName}:`, error.message);
    throw error;
  }
}
