import { googleSheets, spreadsheetId } from "../src/lib/google/client";

const SCHEMA = {
  "01_Students": [
    "UUID",
    "Student Name",
    "Grade",
    "Board",
    "Parent Name",
    "Parent Email",
    "Parent WhatsApp",
    "Mentor",
    "Academic Coordinator",
    "Enrollment Date",
    "Status",
    "Overall Progress Score",
    "Health Status",
    "Created At",
    "Updated At",
  ],
  "02_Subjects": ["Subject ID", "Subject"],
  "03_Student_Subjects": [
    "UUID",
    "Subject ID",
    "Mentor",
    "Start Date",
    "End Date",
    "Status",
  ],
  "04_Classes": [
    "Class ID",
    "Student UUID",
    "Subject",
    "Chapter",
    "Date",
    "Duration",
    "Attendance",
    "Participation %",
    "Homework Given",
    "Homework Completed",
    "Revision Notes Shared",
    "Remarks",
    "Created By",
    "Timestamp",
  ],
  "05_Assignments": [
    "Assignment ID",
    "Student UUID",
    "Subject",
    "Chapter",
    "Assignment Title",
    "Assigned Date",
    "Due Date",
    "Submission Status",
    "Score",
    "Total Marks",
    "Percentage",
    "Mentor Remarks",
  ],
  "06_Chapter_Tests": [
    "Test ID",
    "Student UUID",
    "Subject",
    "Chapter",
    "Test Name",
    "Date",
    "Marks Obtained",
    "Total Marks",
    "Percentage",
    "Mentor Comment",
  ],
  "07_School_Exams": [
    "Exam ID",
    "Student UUID",
    "Subject",
    "Exam Name",
    "Date",
    "Marks",
    "Total",
    "Percentage",
    "Previous Percentage",
    "Improvement %",
  ],
  "08_Learning_Plans": [
    "Plan ID",
    "Student UUID",
    "Subject",
    "Month",
    "Strengths",
    "Weak Areas",
    "Goals",
    "Mentor Plan",
    "Parent Focus",
    "Created By",
    "Created At",
  ],
  "09_PTMs": [
    "PTM ID",
    "Student UUID",
    "Subject",
    "PTM Date",
    "Parent Concerns",
    "Mentor Recommendations",
    "Action Items",
    "Next PTM Date",
  ],
  "10_Mentor_Notes": [
    "Note ID",
    "Student UUID",
    "Subject",
    "Date",
    "Notes",
    "Include In Report",
  ],
  "11_Reports": [
    "Report ID",
    "UUID",
    "Report Type",
    "Start Date",
    "End Date",
    "Generated By",
    "Generated Date",
    "Drive File ID",
    "PDF URL",
    "Public Token",
    "Public URL",
    "Mode",
    "Status",
    "Snapshot Data",
  ],
  "12_Dashboard_Cache": [
    "Total Students",
    "Active Students",
    "Attendance %",
    "Pending Assignments",
    "Reports Pending",
    "Average Score",
    "Average Progress",
    "Students At Risk",
    "Updated At",
  ],
  "13_Settings": [
    "Attendance Weight",
    "Assignment Weight",
    "Participation Weight",
    "Homework Weight",
    "Chapter Test Weight",
    "School Exam Weight",
  ],
  "14_Audit_Log": [
    "Action",
    "User",
    "Time",
    "Student UUID",
    "Module",
    "Description",
  ],
};

async function seed() {
  if (!spreadsheetId) {
    console.error("❌ GOOGLE_SPREADSHEET_ID is not configured in environment.");
    process.exit(1);
  }

  console.log(`🤖 Starting Google Spreadsheet seeding for ID: ${spreadsheetId}`);

  try {
    // 1. Get existing worksheets
    const response = await googleSheets.spreadsheets.get({
      spreadsheetId,
    });
    const existingSheets =
      response.data.sheets?.map((s) => s.properties?.title) || [];
    console.log("📂 Current worksheets found:", existingSheets);

    // 2. Create missing worksheets
    for (const [sheetName, headers] of Object.entries(SCHEMA)) {
      if (!existingSheets.includes(sheetName)) {
        console.log(`➕ Creating sheet: ${sheetName}`);
        await googleSheets.spreadsheets.batchUpdate({
          spreadsheetId,
          requestBody: {
            requests: [
              {
                addSheet: {
                  properties: {
                    title: sheetName,
                  },
                },
              },
            ],
          },
        });
      }

      // 3. Write/Overwrite headers on A1
      console.log(`✍️  Writing headers for sheet: ${sheetName}`);
      await googleSheets.spreadsheets.values.update({
        spreadsheetId,
        range: `${sheetName}!A1`,
        valueInputOption: "RAW",
        requestBody: {
          values: [headers],
        },
      });
    }

    // 4. Populate default Subjects if empty
    const subjectsCheck = await googleSheets.spreadsheets.values.get({
      spreadsheetId,
      range: "02_Subjects!A2:B",
    });
    if (!subjectsCheck.data.values || subjectsCheck.data.values.length === 0) {
      console.log("📝 Seeding default subjects...");
      const defaultSubjects = [
        ["SUB001", "Mathematics"],
        ["SUB002", "Physics"],
        ["SUB003", "Chemistry"],
        ["SUB004", "Biology"],
        ["SUB005", "English"],
        ["SUB006", "ICT"],
      ];
      await googleSheets.spreadsheets.values.append({
        spreadsheetId,
        range: "02_Subjects!A2",
        valueInputOption: "RAW",
        requestBody: {
          values: defaultSubjects,
        },
      });
    }

    // 5. Populate default Settings if empty
    const settingsCheck = await googleSheets.spreadsheets.values.get({
      spreadsheetId,
      range: "13_Settings!A2:F",
    });
    if (!settingsCheck.data.values || settingsCheck.data.values.length === 0) {
      console.log("📝 Seeding default settings weights...");
      const defaultSettings = [
        ["0.15", "0.20", "0.15", "0.15", "0.20", "0.15"], // weights must sum to 1.00
      ];
      await googleSheets.spreadsheets.values.append({
        spreadsheetId,
        range: "13_Settings!A2",
        valueInputOption: "RAW",
        requestBody: {
          values: defaultSettings,
        },
      });
    }

    console.log("✅ Google Spreadsheet seeding completed successfully!");
  } catch (error: any) {
    console.error("❌ Seeding failed:", error?.message || error);
    process.exit(1);
  }
}

seed();
